"""add_case_insensitive_unique_index_to_user

Revision ID: 214ae6990f4d
Revises: bf3726417694
Create Date: 2025-10-28 16:41:33.263050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214ae6990f4d'
down_revision = 'bf3726417694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_users_username_case_insensitive',
        'users',
        [sa.text('lower(username)')],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_case_insensitive', table_name='users')
    # ### end Alembic commands ###