"""Aplicar validaciones de longitud a Contacto y Email

Revision ID: 4707dfbdeaf8
Revises: 6b895dd29f97
Create Date: 2025-10-29 08:26:37.793398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4707dfbdeaf8'
down_revision = '6b895dd29f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
