"""Añadir image_url y notes a Contacto

Revision ID: 6b895dd29f97
Revises: 214ae6990f4d
Create Date: 2025-10-29 07:25:23.711969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b895dd29f97'
down_revision = '214ae6990f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username_case_insensitive'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username_case_insensitive'), [sa.literal_column('lower(username::text)')], unique=True)

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
