"""increase_image_url_length

Revision ID: 721bae46793a
Revises: 4707dfbdeaf8
Create Date: 2025-11-03 14:26:49.385822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721bae46793a'
down_revision = '4707dfbdeaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
