"""Add refresh_token to User model

Revision ID: bf3726417694
Revises: 0f6cea370b81
Create Date: 2025-10-27 11:11:41.880200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3726417694'
down_revision = '0f6cea370b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefonos')
    op.drop_table('emails')
    op.drop_table('contactos')
    op.drop_table('users')
    # ### end Alembic commands ###
